apiVersion: v1
kind: Service
metadata:
  name: fortumars-service
spec:
  type: NodePort   # use LoadBalancer on cloud
  selector:
    app: fortumars
  ports:
    - protocol: TCP
      port: 80
      targetPort: 10000
      nodePort: 30007
